### ISSUE TITLE
Red Black Tree defect

### ISSUE THREAD

**Issue by sriparim** [monkey/monkey#260]
This is regard monkey server encountering issue in mk_sched_add_connection() - following snippet

__start
    event = &conn->event;
    event->fd           = remote_fd;
    event->type         = MK_EVENT_CONNECTION;
    event->mask         = MK_EVENT_EMPTY;
    event->status       = MK_EVENT_NONE;
…..
…..
        struct mk_sched_conn *this = container_of(*new, struct mk_sched_conn, _rb_head);

        parent = *new;
        if (conn->event.fd < this->event.fd)
            new = &((*new)->rb_left);
        else if (conn->event.fd > this->event.fd)
            new = &((*new)->rb_right);
        else {        
            mk_bug(1);
__end

The conn->event.fd is set to remote_fd before the above code snippet.  

The code is hitting the mk_bug()  and at the point, looks like the conn->event.fd and this->event.fd are matching - indicating that the mk_sched_conn node with the fd is still present in the RB tree. 

How to reproduce

We are running a tool called Qualsys Vulnerability Management tool - it is a licensed tool - but you could also the same tool from the following web-site (hopefully it has same tests)

https://www.ssllabs.com/projects/ssllabs-apis/

https://github.com/ssllabs/ssllabs-scan/

**Comment by edsiper** [comment]
hi @sriparim , thanks for the report. would you please confirm the version where you are seeing this problem ? (branch 1.6?)

**Comment by edsiper** [comment]
Patch pushed to workaround the problem in the meanwhile troubleshooting is done

**Comment by edsiper** [comment]
@sriparim 

do you know if is possible to run sslabs-scan tool locally ?, I tried setting up a fake host name but it complains about domain resolution:

```
$ ./ssllabs-scan monkey-ssl.local
2017/02/07 10:12:16 [INFO] SSL Labs v1.27.0 (criteria version 2009m)
2017/02/07 10:12:16 [NOTICE] Server message: This assessment service is provided free of charge by Qualys SSL Labs, subject to our terms and conditions: https://www.ssllabs.com/about/terms.html
2017/02/07 10:12:19 [INFO] Assessment starting: monkey-ssl.local
2017/02/07 10:12:24 [WARN] Assessment failed: monkey-ssl.local (Unable to resolve domain name)
[
{
  "host": "monkey-ssl.local",
  "port": 443,
  "protocol": "HTTP",
  "isPublic": false,
  "status": "ERROR",
  "statusMessage": "Unable to resolve domain name",
  "startTime": 1486483937686,
  "testTime": 1486483937736,
  "engineVersion": "1.27.0",
  "criteriaVersion": "2009m",
  "cacheExpiryTime": 1486483997736
}
]
```

**Comment by sriparim** [comment]
Apologies for delay - answers to your questions
Q1-ans: We are using 1.6.9 version

Q2-ans: As far as I could make out from the documentation, it expects the test server to be on the public network. The tests and the report generation happens in the SSL labs servers. But I will find out from the team here and see if I it is possible to run locally. Since you have committed the work around patch, I will pull it and test it on your behalf and let you know.

**Comment by sriparim** [comment]
@edsiper 

We applied the changes that you made (temporary work around to delete the rb_queue node with same fd).

When we ran the Qualys SSL scan and also another HTTPS general request/response session parallely, found that monkey stops responding.

	1. In our configuration of one worker thread, both the server and worker thread are in RUNNING STATE (they should be in SLEEP STATE). 

	2. Following is the stack trace of WORKER thread. It seems to be stuck in rb_erase()

0x000280c8 in rb_erase ()
(gdb) bt
#0  0x000280c8 in rb_erase ()
#1  0x00011880 in mk_sched_remove_client ()
#2  0x000119b4 in mk_sched_drop_connection ()
#3  0x00011e08 in mk_sched_event_close ()
#4  0x0001baa8 in mk_server_worker_loop ()
#5  0x00011680 in mk_sched_launch_worker_loop ()
#6  0x40030850 in ?? () from /lib/libpthread.so.0
#7  0x40030850 in ?? () from /lib/libpthread.so.0

	3. Stack trace of SERVER thread

#0  0x000111ec in mk_sched_add_connection ()
#1  0x0001ae34 in ?? ()
#2  0x0001ae34 in ?? ()

Could you please review the change and let us know ? IF you need some more data, please let me know
